import { ui } from '../runtime.js';
import { addUrlHandler, openExternal } from '../url-hub.js';
export function AlwaysAnimate(r) {
    const { h, React, RN } = r, { Page, Text, Toggle } = ui(r); let reduced = false;
    return { async start() { reduced = await RN.AccessibilityInfo?.isReduceMotionEnabled?.() || false; const listener = RN.AccessibilityInfo?.addEventListener?.('reduceMotionChanged', value => { reduced = value; }); r.own(() => listener?.remove()); r.hook(['Emoji', 'CustomEmoji', 'Avatar', 'GuildIcon', 'GuildBanner', 'Nameplate', 'RoleIcon'], element => { if (!element || (reduced && r.store.respectReducedMotion)) return; const props = {}; for (const key of ['canAnimate', 'animate', 'animateEmoji', 'animateGradient', 'loop']) if (typeof element.props?.[key] === 'boolean') props[key] = true; return Object.keys(props).length ? React.cloneElement(element, props) : undefined; }); }, Settings() { r.useRefresh(); return h(Page, { title: 'AlwaysAnimate' }, h(Toggle, { setting: 'respectReducedMotion', label: 'Respect Reduce Motion' }), h(Text, null, 'Enables existing animation props on supported emoji, avatar and profile components. Native-rendered chat is unaffected.')); } };
}
AlwaysAnimate.defaults = { respectReducedMotion: true };
export function BlurNsfw(r) {
    const { h, React, RN } = r, { Page, Text, Button, Toggle } = ui(r), Gate = React.createContext(false);
    function Media({ original }) { const nested = React.useContext(Gate), [shown, reveal] = React.useState(false); if (nested) return original; return h(Gate.Provider, { value: true }, h(RN.View, null, shown ? original : h(RN.View, {style:{height:100,justifyContent:'center',padding:12}}, h(Text,null,'Sensitive media hidden')), h(Button, { text: shown ? 'Hide sensitive media' : 'Reveal sensitive media', variant: 'secondary', onPress: () => reveal(v => !v) }))); }
    return { start() { r.hook(['MessageImage', 'MessageVideo', 'MessageAttachment', 'ImageAttachment', 'VideoAttachment'], element => { const p = element?.props || {}, a = p.attachment; if (a && !/^(image|video)\//.test(a.content_type || a.contentType || '') && !/\.(png|jpe?g|gif|webp|mp4|mov)$/i.test(a.filename || '')) return; const channel = p.channel || r.byStore('ChannelStore')?.getChannel?.(p.channelId || p.channel_id || p.message?.channel_id || p.message?.channelId); if (r.store.blurAllChannels || channel?.nsfw) return h(Media, { original: element }); }); }, Settings() { r.useRefresh(); return h(Page, { title: 'BlurNSFW' }, h(Toggle, { setting: 'blurAllChannels', label: 'Hide media in every channel' }), h(Text, null, 'Mobile uses a tap-to-reveal cover. Native chat rows without JSX hooks cannot be covered; do not rely on this as a content filter.')); } };
}
BlurNsfw.defaults = { blurAllChannels: false };
export function NsfwGateBypass(r) { const { h } = r, { Page, Text } = ui(r); return { start() { let count = 0; for (const name of ['isNSFWInvite', 'shouldNSFWGateGuild']) { if (r.patch('after', r.find(name), name, () => false)) count++; } r.status.support = count ? `${count} client gate hooks installed` : 'Unsupported: mobile gate functions were not found'; }, Settings() { return h(Page, { title: 'NSFWGateBypass' }, h(Text, null, r.status.support), h(Text, { muted: true }, 'Removes supported local guild interstitials. Server permissions and account restrictions remain enforced.')); } }; }
export function appLink(value) { try { const u = new URL(value); if (u.protocol !== 'https:' || u.username || u.password) return null; if (u.hostname === 'open.spotify.com' && /^\/(?:intl-[a-z-]+\/)?(?:track|album|artist|playlist|episode|show)\/[A-Za-z0-9]+\/?$/.test(u.pathname)) return 'spotify:' + u.pathname.replace(/^\/(?:intl-[a-z-]+\/)?/, '').replace(/\/$/, '').replace('/', ':'); if (['store.steampowered.com', 'steamcommunity.com'].includes(u.hostname)) return 'steam://openurl/' + u.href; if (u.hostname === 'tidal.com' && /^\/browse\/(track|album|artist|playlist)\/[\w-]+\/?$/.test(u.pathname)) return 'tidal://' + u.pathname.slice(8); if (u.hostname === 'music.apple.com') return 'musics://' + u.host + u.pathname + u.search; if (u.hostname === 't.me' && /^\/[A-Za-z][\w]{4,}\/?$/.test(u.pathname)) return 'tg://resolve?domain=' + encodeURIComponent(u.pathname.slice(1).replace(/\/$/, '')); } catch {} return null; }
export function OpenInApp(r) { const { h } = r, { Page, Text, Toggle } = ui(r); return { start() { addUrlHandler(r, 10, (url, fallback) => { const app = appLink(url); if (!r.store.enabled || !app) return false; Promise.resolve(r.RN.Linking.canOpenURL(app)).then(async supported => { if (!r.active) return; if (supported) { try { await openExternal(r, app); return; } catch {} } fallback(); }).catch(() => r.active && fallback()); return true; }); }, Settings() { r.useRefresh(); return h(Page, { title: 'OpenInApp' }, h(Toggle, { setting: 'enabled', label: 'Open supported links in their app' }), h(Text, null, 'Spotify, Steam, Tidal, Apple Music and public Telegram usernames. Falls back when an app is unavailable. SpotifyPreview takes priority. iOS scheme allowlists may limit detection.')); } }; }
OpenInApp.defaults = { enabled: true };
export function ValidUser(r) {
    const { h, React } = r, { Page, Text, Button, Input } = ui(r); const pending = new Map(); let next = 0;
    async function resolve(id) { if (!/^\d{16,22}$/.test(id)) throw new Error('Enter a numeric Discord user ID'); if (pending.has(id)) return pending.get(id); const cached = r.byStore('UserStore')?.getUser?.(id); if (cached?.username) return cached; if (Date.now() < next) throw new Error('Wait a moment before another lookup'); next = Date.now() + 1500; const task = r.discord(`/users/${id}`).then(result => { const user = result.json(); if (!user?.id || !user?.username) throw new Error('User could not be resolved'); r.common.FluxDispatcher?.dispatch?.({ type: 'USER_UPDATE', user }); return user; }).finally(() => pending.delete(id)); pending.set(id, task); return task; }
    function Settings() { const [id, setId] = React.useState(''), [result, setResult] = React.useState(''), [busy, setBusy] = React.useState(false); return h(Page, { title: 'ValidUser' }, h(Input, { label: 'User ID', value: id, onChange: setId, keyboardType: 'number-pad' }), h(Button, { text: busy ? 'Resolving…' : 'Resolve user', disabled: busy, onPress: () => { setBusy(true); resolve(id.trim()).then(u => setResult(`${u.global_name || u.globalName || u.username} (@${u.username})`)).catch(e => setResult(e.message)).finally(() => setBusy(false)); } }), h(Text, null, result || 'Mobile lookup populates available user data. Desktop hover and inferred badges are not reproduced.')); }
    return { start() { r.command({ name: 'resolveuser', description: 'Resolve a Discord user ID locally', options: [{ name: 'id', description: 'User ID', type: 3, required: true }], async execute(options) { const user = await resolve(String(options.find(o => o.name === 'id')?.value || '')); r.toast(`${user.global_name || user.username} (@${user.username})`); } }); }, Settings, resolve };
}
export function PauseInvitesForever(r) {
    const { h, React } = r, { Page, Text, Button } = ui(r);
    function Confirm({ guildId, pause, close }) {
        const [busy, setBusy] = React.useState(false), inFlight = React.useRef(false), mounted = React.useRef(true);
        React.useEffect(() => () => { mounted.current = false; }, []);
        return h(Page, { title: pause ? 'Pause server invites indefinitely?' : 'Resume server invites?', close }, h(Text, null, `Server: ${r.byStore('GuildStore')?.getGuild?.(guildId)?.name || guildId}. This changes the invite setting for everyone and requires server permissions.`),
            h(Button, { text: busy ? 'Saving…' : pause ? 'Pause invites' : 'Resume invites', disabled: busy, onPress: async () => {
                if (inFlight.current) return; inFlight.current = true; setBusy(true);
                try {
                    const guild = (await r.discord(`/guilds/${guildId}`)).json();
                    if (!Array.isArray(guild?.features)) throw new Error('Could not read current server features');
                    const features = guild.features.filter(f => f !== 'INVITES_DISABLED'); if (pause) features.push('INVITES_DISABLED');
                    await r.discord(`/guilds/${guildId}`, { method: 'PATCH', body: JSON.stringify({ features }) });
                    r.toast(pause ? 'Invites paused' : 'Invites resumed'); if (mounted.current) close();
                } catch (e) { if (r.active) r.error('Server invites', e); }
                finally { inFlight.current = false; if (r.active && mounted.current) setBusy(false); }
            } }));
    }
    return { start() { for (const pause of [true, false]) r.command({ name: pause ? 'pauseinvites' : 'resumeinvites', description: pause ? 'Pause server invites without a timer' : 'Resume server invites', execute(_options, context) {
        const channel = context?.channel || r.byStore('ChannelStore')?.getChannel?.(context?.channelId);
        const guildId = context?.guild?.id || context?.guildId || channel?.guild_id || channel?.guildId;
        if (!/^\d+$/.test(guildId || '')) throw new Error('Run this in a server channel'); r.open('confirm', Confirm, { guildId, pause });
    } }); }, Settings() { return h(Page, { title: 'PauseInvitesForever' }, h(Text, null, 'Use /pauseinvites or /resumeinvites in a server. A confirmation appears before changing anything. Current server features are preserved; Discord validates your permissions.')); }, Confirm };
}
export function VolumeBooster(r) { const { h } = r, { Page, Text } = ui(r); return { start() {}, Settings() { return h(Page, { title: 'VolumeBooster · compatibility probe' }, h(Text, null, 'Unavailable: no verified native gain API above Discord’s volume ceiling.'), h(Text, { muted: true }, 'Desktop uses Web Audio gain nodes. A mobile port needs a documented native voice/audio hook.')); } }; }
export function shouldPing(message, channel, oldestUnread, settings, selfId) { if (![1,3].includes(channel?.type) || String(settings.ignoreUsers || '').split(/[\s,]+/).includes(message.author?.id)) return true; if ((channel.type === 1 && settings.channelToAffect === 'group_dm') || (channel.type === 3 && settings.channelToAffect === 'user_dm')) return true; if (settings.allowMentions && message.mentions?.some(m => (m.id || m) === selfId)) return true; if (settings.allowEveryone && (message.mention_everyone || message.mentionEveryone)) return true; return !oldestUnread || oldestUnread === message.id; }
export function OnePingPerDM(r) { const { h } = r, { Page, Text } = ui(r); return { start() {}, Settings() { return h(Page, { title: 'OnePingPerDM · compatibility probe' }, h(Text, null, 'Port blocked: no verified message-aware mobile notification sound hook.'), h(Text, { muted: true }, 'The desktop unread/mention policy is ported and tested, but is not attached to live audio. Messages and notifications are left intact.')); } }; }
